routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('master/vendor', 'Master\VendorController');
Route::get('vendor/datatable', 'Master\VendorController@datatable')->name('vendor/datatable');

Route::resource('master/product', 'Master\ProductController');
Route::get('product/datatable', 'Master\ProductController@datatable')->name('product/datatable');
Route::get('product/datatableTrash', 'Master\ProductController@datatableTrash')->name('product/datatableTrash');
Route::post('product/undoTrash/{id}','Master\ProductController@undotrash')->name('product/undoTrash/{id}');
Route::get('master/product/history/{id}', 'Master\ProductController@history')->name('master/product/history/{id}');

Route::resource('transaction/purchase-order', 'Transaction\PurchaseController');
Route::get('transaction/purchase-order/vendor/popup_media', 'Transaction\PurchaseController@popup_media_vendor')->name('transaction/purchase-order/vendor/popup_media');
Route::get('transaction/purchase-order/product/popup_media/{id_count}', 'Transaction\PurchaseController@popup_media_product')->name('transaction/purchase-order/product/popup_media/{id_count}');
Route::get('browse-vendor/datatable','Master\VendorController@datatable_vendor')->name('browse-vendor/datatable');
Route::get('browse-product/datatable','Master\ProductController@datatable_product')->name('browse-product/datatable');
Route::get('purchase-order/datatable','Transaction\PurchaseController@datatable')->name('purchase-order/datatable');
Route::post('transaction/purchase-order/receive/{id}', 'Transaction\PurchaseController@received')->name('transaction/purchase-order/received/{id}');

Route::resource('transaction/sales', 'Transaction\SaleController');
Route::get('transaction/sales/product/popup_media/{id_count}', 'Transaction\PurchaseController@popup_media_product')->name('transaction/sales/product/popup_media/{id_count}');
Route::get('sales/datatable','Transaction\SaleController@datatable')->name('sales/datatable');
Route::get('transaction/sales/print/{id}','Transaction\SaleController@print')->name('transaction/sales/print/{id}');

Route::get('transaction/stock', 'Transaction\StockController@index')->name('transaction/stock');
Route::get('transaction/stock/product/popup_media', 'Transaction\StockController@popup_media_product')->name('transaction/stock/product/popup_media');
Route::post('transaction/stock', 'Transaction\StockController@update')->name('transaction/stock');
Route::get('stock/report', 'Transaction\StockController@report')->name('stock/report');

app/Http/Controllers/Master/VendorController.php
<?php

namespace App\Http\Controllers\Master;

use App\Http\Controllers\Controller;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Yajra\DataTables\DataTables;
use TJGazel\Toastr\Facades\Toastr;
use App\Model\Master\Vendor;

class VendorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('Vendor.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Vendor.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = new Vendor();
        $data->name = $request->name;
        $data->address = $request->address;
        $data->cp = $request->contactPerson;
        $data->phone = $request->phone;
        $data->active = $request->status;
        $data->user_modified = Auth::user()->id;


        if (Vendor::where('name', $data->name)
            ->orWhere('address', $data->address)
            ->orWhere('phone', $data->phone)->exists()) {
            Toastr::error("Name/ address/ phone already Exist", 'Error');
            return redirect()->back();
        }
        else if ($data->save()){
            $data->save();
            Toastr::success("Vendor created successfuly", 'Success');
            return redirect()->route('vendor.index');
        }
        else{
            Toastr::error("Input cant be empty", 'Error');
            return redirect()->back();
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = Vendor::with(['user_modify'])->where('id', $id)->get();
        if($data->count() > 0){
            return view('vendor.view', compact('data'));
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Vendor::where('id', $id)->where('active', '!=', 2)->get();
        if($data->count() > 0){
            return view('vendor.update', compact('data'));
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = Vendor::find($id);
        $data->name = $request->name;
        $data->address = $request->address;
        $data->cp = $request->contactPerson;
        $data->phone = $request->phone;
        $data->active = $request->status;
        $data->user_modified = Auth::user()->id;

        if (DB::table('vendors')->where('id','!=', $id)
            ->where(function ($query) use ($data){
                $query->orWhere('name', $data->name)
                ->orWhere('address', $data->address)
                ->orWhere('phone', $data->phone);
            })
            ->exists()) {
            Toastr::error("Name/ address/ phone already Exist", 'Error');
            return redirect()->back();
        }
        else if ($data->save()){
            Toastr::success("Vendor updated successfuly", 'Success');
            return redirect()->route('vendor.index');
        }
        else{
            Toastr::error("Vendor cannot be updated successfully", 'Error');
            return redirect()->back();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Vendor::find($id);
        $data->active = 2;
        $data->user_modified = Auth::user()->id;

        if ($data->save()){
            Toastr::success("Vendor deleted successfuly", 'Success');
            return new JsonResponse(['status'=>true]);
        }
        else{
            Toastr::error("Vendor cannot be deleted successfully", 'Error');
            return new JsonResponse(['status'=>false]);
        }
    }

    public function datatable(){
        $data = Vendor::where('active', '!=', 2);
        return Datatables::of($data)
            ->addColumn('action', function($data){
                
                $url_edit = url('master/vendor/'.$data->id.'/edit');
                $url = url('master/vendor/'.$data->id);
                
                $view = "<a class='btn btn-action btn-primary' href='$url' title='View'><i class='nav-icon fas fa-eye'></i></a>";
                $edit = "<a class='btn btn-action btn-warning' href='$url_edit' title='Edit'><i class='nav-icon fas fa-edit'></i></a>";
                $delete = "<button data-url='$url' onclick='deleteData(this)' class='btn btn-action btn-danger' title='Delete'><i class='nav-icon fas fa-trash-alt'></i></button>";
                
                return $view."".$edit."".$delete;
            })
            ->editColumn('address', function($data){
                return str_ireplace('\r\n', ',', $data->address);
            })
            ->editColumn('phone', function($data){
                return str_ireplace('\r\n', ',', $data->phone);
            })
            ->rawColumns(['action'])
            ->editColumn('id', 'ID: {{$id}}')
            ->make(true);
    }       

    public function datatable_vendor(){
        $data = Vendor::select('vendors.*')->where('vendors.active', '!=', 2);

        return Datatables::of($data)
            ->editColumn('address', function($data){
                return str_ireplace("\r\n", ',', $data->address);
            })
            ->make(true);
    }
}

resources/views/Vendor/create.blade.php
@extends('layouts.backend.app')

@section('content')
    
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0 text-dark">Vendor</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item">Master</li>
                <li class="breadcrumb-item active">Create Vendor</li>
              </ol>
            </div><!-- /.col -->
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content-header -->

          <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
          <div class="row">
            <!-- left column -->
            <div class="col-md-12">
              <!-- Horizontal Form -->
              <div class="card card-info">
                <div class="card-header">
                  <h3 class="card-title">Create Vendor</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form class="form-horizontal" method="POST" action="{{route('vendor.store')}}">
                    @csrf
                  <div class="card-body">
                    <div class="form-group row">
                        <div class="col-md-4">
                            <label for="name" class="col-sm-4 col-form-label">Name</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="name" name="name" placeholder="Name">
                            </div>
                        </div>
                    
                        <div class="col-md-4">
                            <label for="address" class="col-sm-4 col-form-label">Address</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="address" name="address" placeholder="Address">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <label for="contactPerson" class="col-sm-6 col-form-label">Contact Person</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="contactPerson" name="contactPerson" placeholder="Contact Person">
                            </div>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-4">
                            <label for="phone" class="col-sm-4 col-form-label">Phone No</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="phone" name="phone" placeholder="Phone No">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <label for="address" class="col-sm-4 col-form-label">Status</label>
                            <div class="col-sm-8">
                                <select class="form-control" id="status" name="status">
                                    <option value="1">Active</option>
                                    <option value="0">Inactive</option>
                                </select>
                            </div>
                        </div>
                    </div>
                  </div> <!-- /.card-body -->
              
              <div class="card-footer">
                <button type="submit" class="btn btn-default float-right">Submit</button>
              </div><!-- /.card-footer -->
                </form>
              </div> <!-- /.card-info -->
            </div>
            <!--/.col (left) -->
          </div>
          <!-- /.row -->
        </div><!-- /.container-fluid -->
      </section>
      <!-- /.content -->
      
@endsection

resources/views/Vendor/index.blade.php
@extends('layouts.backend.app')

@push('css')
    <!-- DataTables -->
    <link rel="stylesheet" href="{{asset('asset/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css')}}">
    <link rel="stylesheet" href="{{asset('asset/plugins/datatables-responsive/css/responsive.bootstrap4.min.css')}}">
@endpush

@section('content')

    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0 text-dark">Vendor</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item">Master</li>
                <li class="breadcrumb-item active">Vendor</li>
              </ol>
            </div><!-- /.col -->
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content-header -->

          <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Vendor List</h3>
              <a class="btn btn-info btn-sm float-right" href="{{route('vendor.create')}}" title="Create">Create</a>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example1" class="table table-bordered table-striped" style="width: 100%">
                  <thead>
                  <tr>
                    <th>Name</th>
                    <th>Address</th>
                    <th>Contact Person</th>
                    <th>Phone</th>
                    <th>Status</th>
                    <th>Action</th>
                  </tr>
                  </thead>
                  
                  <tfoot>
                  <tr>
                    <th>Name</th>
                    <th>Address</th>
                    <th>Contact Person</th>
                    <th>Phone</th>
                    <th>Status</th>
                    <th>Action</th>
                  </tr>
                  </tfoot>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </section> <!-- /.Main content -->

@endsection

@push('js')
  <!-- DataTables -->
  <script src="{{asset('asset/plugins/datatables/jquery.dataTables.min.js')}}"></script>
  <script src="{{asset('asset/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js')}}"></script>
  <script src="{{asset('asset/plugins/datatables-responsive/js/dataTables.responsive.min.js')}}"></script>
  <script src="{{asset('asset/plugins/datatables-responsive/js/responsive.bootstrap4.min.js')}}"></script>

  <!-- page script -->
  <script>
    $(function () {
      $("#example1").DataTable({
        "responsive": true,
        "processing": true,
        "pagingType": 'full_numbers',
        "stateSave": false,
        "scrollY": true,
        "scrollX": true,
        ajax:"{{ url('vendor/datatable') }}",
        order: [0,'desc'],
        columns:[
          {data:'name', name:'name'},
          {data:'address', name:'address'},
          {data:'cp', name:'cp'},
          {data:'phone', name:'phone'},
          {data:'active',
                render:function(data){
                  if(data=='1'){
                    return '<span class="badge badge-success">Active</span>';
                  }
                  if(data=='0'){
                    return '<span class="badge badge-warning">Inactive</span>';
                  }
                },
          },
          {data:'action', name:'action', searchable: false, sortable:false}
        ]
      });
    });
  </script>

  <script>
    // Confirmation delete data
    function deleteData(dt){
      if(confirm("Are you sure want to delete this data?")){
        $.ajax({
          type: 'DELETE',
          url:$(dt).data("url"),
          data:{
            "_token":"{{csrf_token()}}"
          },
          success:function (response){
            if(response.status){
              location.reload();
            }
          },
          error:function(response){
            console.log(response);
          }
        });
      }
      return false;
    }
  </script>
@endpush

resources/views/Vendor/update.blade.php
@extends('layouts.backend.app')

@section('content')
    
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0 text-dark">Vendor</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item">Mater</li>
                <li class="breadcrumb-item active">Create Vendor</li>
              </ol>
            </div><!-- /.col -->
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content-header -->

          <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
          <div class="row">
            <!-- left column -->
            <div class="col-md-12">
              <!-- Horizontal Form -->
              <div class="card card-info">
                <div class="card-header">
                  <h3 class="card-title">Create Vendor</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form class="form-horizontal" method="POST" action="{{route('vendor.update', $data[0]->id)}}">
                    @method('PUT')
                    @csrf
                  <div class="card-body">
                    <div class="form-group row">
                        <div class="col-md-4">
                            <label for="name" class="col-sm-4 col-form-label">Name</label>
                            <div class="col-sm-8">
                            <input type="text" class="form-control" id="name" name="name" value="{{$data[0]->name}}" placeholder="Name">
                            </div>
                        </div>
                    
                        <div class="col-md-4">
                            <label for="address" class="col-sm-4 col-form-label">Address</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="address" name="address" value="{{$data[0]->address}}" placeholder="Address">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <label for="contactPerson" class="col-sm-6 col-form-label">Contact Person</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="contactPerson" name="contactPerson" value="{{$data[0]->cp}}" placeholder="Contact Person">
                            </div>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-4">
                            <label for="phone" class="col-sm-4 col-form-label">Phone No</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="phone" name="phone" value="{{$data[0]->phone}}" placeholder="Phone No">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <label for="address" class="col-sm-4 col-form-label">Status</label>
                            <div class="col-sm-8">
                                <select class="form-control" id="status" name="status">
                                    <option value="1" {{$data[0]->active===1 ? 'selected' : ''}}>Active</option>
                                    <option value="0" {{$data[0]->active===0 ? 'selected' : ''}}>Inactive</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-4">
                            
                        </div>
                    </div>
                </div>

              </div>
                <!-- /.card-body -->
                <div class="card-footer">
                <button type="submit" class="btn btn-default float-right">Submit</button>
                </div>
                <!-- /.card-footer -->
                </form>
              </div>
              <!-- /.card -->
  
            </div>
            <!--/.col (left) -->
          </div>
          <!-- /.row -->
        </div><!-- /.container-fluid -->
      </section>
      <!-- /.content -->
      
@endsection

resources/views/Vendor/view.blade.php
@extends('layouts.backend.app')

@section('content')
    
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0 text-dark">Vendor</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item">Mater</li>
                <li class="breadcrumb-item active">View Vendor</li>
              </ol>
            </div><!-- /.col -->
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content-header -->

          <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
          <div class="row">
            <!-- left column -->
            <div class="col-md-12">
              <!-- Horizontal Form -->
              <div class="card card-info">
                <div class="card-header">
                  <h3 class="card-title">View Vendor</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form class="form-horizontal" action="{{route('vendor.update', $data[0]->id)}}">
                    @csrf
                  <div class="card-body">
                    <div class="form-group row">
                        <div class="col-md-4">
                            <label for="name" class="col-sm-4 col-form-label">Name</label>
                            <div class="col-sm-8">
                            <input type="name" class="form-control" id="name" name="name" value="{{$data[0]->name}}" placeholder="Name" disabled>
                            </div>
                        </div>
                    
                        <div class="col-md-4">
                            <label for="address" class="col-sm-4 col-form-label">Address</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="address" name="address" value="{{$data[0]->address}}" placeholder="Address" disabled>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <label for="contactPerson" class="col-sm-6 col-form-label">Contact Person</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="contactPerson" name="contactPerson" value="{{$data[0]->cp}}" placeholder="Contact Person" disabled>
                            </div>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-4">
                            <label for="phone" class="col-sm-4 col-form-label">Phone No</label>
                            <div class="col-sm-8">
                                <input type="phone" class="form-control" id="phone" name="phone" value="{{$data[0]->phone}}" placeholder="Phone No" disabled>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <label for="address" class="col-sm-4 col-form-label">Status</label>
                            <div class="col-sm-8">
                                <select class="form-control" id="status" name="status" disabled>
                                    <option value="1" {{$data[0]->active===1 ? 'selected' : ''}}>Active</option>
                                    <option value="0" {{$data[0]->active===0 ? 'selected' : ''}}>Inactive</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <label for="user-modified" class="col-sm-4 col-form-label">User Modified</label>
                            <div class="col-sm-8">
                                <input type="user-modified" class="form-control" id="user-modified" name="user-modified" value="{{$data[0]->user_modify->name}}" placeholder="User Modified" disabled>
                            </div>
                        </div>
                    </div>
                </div>

              </div>
                <!-- /.card-body -->
                </form>
              </div>
              <!-- /.card -->
  
            </div>
            <!--/.col (left) -->
          </div>
          <!-- /.row -->
        </div><!-- /.container-fluid -->
      </section>
      <!-- /.content -->
      
@endsection