routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('master/vendor', 'Master\VendorController');
Route::get('vendor/datatable', 'Master\VendorController@datatable')->name('vendor/datatable');

Route::resource('master/product', 'Master\ProductController');
Route::get('product/datatable', 'Master\ProductController@datatable')->name('product/datatable');
Route::get('product/datatableTrash', 'Master\ProductController@datatableTrash')->name('product/datatableTrash');
Route::post('product/undoTrash/{id}','Master\ProductController@undotrash')->name('product/undoTrash/{id}');
Route::get('master/product/history/{id}', 'Master\ProductController@history')->name('master/product/history/{id}');

Route::resource('transaction/purchase-order', 'Transaction\PurchaseController');
Route::get('transaction/purchase-order/vendor/popup_media', 'Transaction\PurchaseController@popup_media_vendor')->name('transaction/purchase-order/vendor/popup_media');
Route::get('transaction/purchase-order/product/popup_media/{id_count}', 'Transaction\PurchaseController@popup_media_product')->name('transaction/purchase-order/product/popup_media/{id_count}');
Route::get('browse-vendor/datatable','Master\VendorController@datatable_vendor')->name('browse-vendor/datatable');
Route::get('browse-product/datatable','Master\ProductController@datatable_product')->name('browse-product/datatable');
Route::get('purchase-order/datatable','Transaction\PurchaseController@datatable')->name('purchase-order/datatable');
Route::post('transaction/purchase-order/receive/{id}', 'Transaction\PurchaseController@received')->name('transaction/purchase-order/received/{id}');

Route::resource('transaction/sales', 'Transaction\SaleController');
Route::get('transaction/sales/product/popup_media/{id_count}', 'Transaction\PurchaseController@popup_media_product')->name('transaction/sales/product/popup_media/{id_count}');
Route::get('sales/datatable','Transaction\SaleController@datatable')->name('sales/datatable');
Route::get('transaction/sales/print/{id}','Transaction\SaleController@print')->name('transaction/sales/print/{id}');

Route::get('transaction/stock', 'Transaction\StockController@index')->name('transaction/stock');
Route::get('transaction/stock/product/popup_media', 'Transaction\StockController@popup_media_product')->name('transaction/stock/product/popup_media');
Route::post('transaction/stock', 'Transaction\StockController@update')->name('transaction/stock');
Route::get('stock/report', 'Transaction\StockController@report')->name('stock/report');

app/Http/Controllers/Master/ProductController.php
<?php

namespace App\Http\Controllers\Master;

use App\Http\Controllers\Controller;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Yajra\DataTables\DataTables;
use TJGazel\Toastr\Facades\Toastr;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Str;
use App\Model\Master\Product;
use App\Model\Purchase\PurchaseD;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('Product.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Product.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(),[
            'code' => 'required|unique:products|max:255',
            'name' => 'required|unique:products|max:255',
        ]);

        if($validator->fails()){
            Toastr::warning('Product code or Product name cannot be repeated.', 'Warning');
            return Redirect::back()->withErrors($validator)->withInput();
        }
        else{
            $data = new Product();
            $data->code = $request->code;
            $data->name = $request->name;
            $data->selling_price = $request->sellingPrice/1;
            $data->purchase_price = $request->purchasePrice/1;
            $data->stock_available = $request->stockAvailable/1;
            $data->stock_total = $request->stockAvailable/1;
            $data->information = $request->information;
            $data->active = $request->status;
            $data->user_modified = $request->user()->id;

            if($data->save()){
                Toastr::success('Product created successfully','Success');
                return redirect()->route('product.index');
            }
            else{
                Toastr::error('Product cannot created successfully','Error');
                return redirect()->back();
            }
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = Product::with(['user_modify'])->where('id', $id)->get();
        if($data->count() > 0){
            return view('Product.view', compact('data'));
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Product::where('id', $id)->where('active', '!=', 2)->get();
        if($data->count() > 0){
            return view('Product.update', compact('data'));
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = Product::find($id);
        $data->code = $request->code;
        $data->name = $request->name;
        $data->selling_price = $request->sellingPrice/1;
        $data->purchase_price = $request->purchasePrice/1;
        $data->stock_available = $request->stockAvailable/1;
        $data->stock_total = $request->stockAvailable/1;
        $data->information = $request->information;
        $data->active = $request->status;
        $data->user_modified = $request->user()->id;

        if($data->save()){
            Toastr::success('Product created successfully','Success');
            return redirect()->route('product.index');
        }
        else{
            Toastr::error('Product cannot created successfully','Error');
            return redirect()->back();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Product::find($id);
        $data->active = 2;
        $data->user_modified = Auth::user()->id;

        if ($data->save()){
            Toastr::success("Product deleted successfuly", 'Success');
            return new JsonResponse(['status'=>true]);
        }
        else{
            Toastr::error("Product cannot be deleted successfully", 'Error');
            return new JsonResponse(['status'=>false]);
        }
    }

    public function datatable(){
        $data = Product::where('active', '!=', 2);
        return Datatables::of($data)
            ->addColumn('action', function($data){
                
                $url_edit = url('master/product/'.$data->id.'/edit');
                $url = url('master/product/'.$data->id);
                $url_history = url('master/product/history/'.$data->id);
    
                $view = "<a class='btn btn-action btn-primary' href='$url' title='View'><i class='nav-icon fas fa-eye'></i></a>";
                $edit = "<a class='btn btn-action btn-warning' href='$url_edit' title='Edit'><i class='nav-icon fas fa-edit'></i></a>";
                $delete = "<button data-url='$url' onclick='deleteData(this)' class='btn btn-action btn-danger' title='Delete'><i class='nav-icon fas fa-trash-alt'></i></button>";
                $history = "<a class='btn btn-action btn-warning' href='$url_history' title='History' data-toggle='modal' data-target='#modal-info'>Purchase Detail</a>";
                
                return $view."".$edit."".$delete."".$history;
            })
            ->editColumn('purchase_price', function($data){
                return number_format($data->purchase_price, 0, '.', ',');
            })
            ->editColumn('selling_price', function($data){
                return number_format($data->selling_price, 0, '.', ',');
            })
            ->editColumn('information', function($data){
                $string_replace = str_ireplace('\r\n', ',', $data->information);
                return str::limit($string_replace, 30, '...');
            })
            ->rawColumns(['action'])
            ->editColumn('id', 'ID: {{$id}}')
            ->make(true);
    } //.datatable  wrapper

    public function datatableTrash(){
        $data = Product::where('active', '=', 2);
        return Datatables::of($data)
            ->addColumn('action', function($data){
                
                $url = url('master/product/'.$data->id);
                $undoTrash = url('product/undoTrash/'.$data->id);
    
                $view = "<a class='btn btn-action btn-primary' href='$url' title='View'><i class='nav-icon fas fa-eye'></i></a>";
                $undo = "<button data-url='$undoTrash' onclick='undoTrash(this)' class='btn btn-action btn-danger' title='Undo Trash'>Activate Product</button>";
                
                return $view."".$undo;
            })
            ->editColumn('purchase_price', function($data){
                return number_format($data->purchase_price, 0, '.', ',');
            })
            ->editColumn('selling_price', function($data){
                return number_format($data->selling_price, 0, '.', ',');
            })
            ->editColumn('information', function($data){
                $string_replace = str_ireplace('\r\n', ',', $data->information);
                return str::limit($string_replace, 30, '...');
            })
            ->rawColumns(['action'])
            ->editColumn('id', 'ID: {{$id}}')
            ->make(true);
    } //.datatableTrash wrapper

    public function undoTrash(Request $request, $id){
        $data = Product::find($id);

        $data->active = 1;
        $data->user_modified = Auth::user()->id;

        if ($data->save()){
            Toastr::success("Product has been activated successfuly", 'Success');
            return new JsonResponse(['status'=>true]);
        }
        else{
            Toastr::error("Product cannot be activated successfully", 'Error');
            return new JsonResponse(['status'=>false]);
        }

    }

    public function datatable_product(){
        $data = Product::select('products.*')->where('products.active', '!=', 0);

        return Datatables::of($data)->make(true);
    }

    public function history($id){
        $datas = PurchaseD::with(['purchase'])->where('id_product', $id)
                        ->orderBy('id', 'DESC')
                        ->limit(5)
                        ->get();
        return view('Product.history', ['datas'=>$datas]);
    }
}

resources/views/Product/create.blade.php
@extends('layouts.backend.app')

@section('content')
    
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0 text-dark">Product</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item active">Mater</li>
                <li class="breadcrumb-item active">Create Product</li>
              </ol>
            </div><!-- /.col -->
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content-header -->

          <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
          <div class="row">
            <!-- left column -->
            <div class="col-md-12">
              <!-- Horizontal Form -->
              <div class="card card-info">
                <div class="card-header">
                  <h3 class="card-title">Create Product</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form class="form-horizontal" method="POST" action="{{route('product.store')}}">
                    @csrf
                  <div class="card-body">
                    <div class="form-group row">
                        <div class="col-md-4">
                            <label for="code" class="col-sm-4 col-form-label">Code</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="code" name="code" placeholder="Code">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <label for="name" class="col-sm-4 col-form-label">Name</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="name" name="name" placeholder="Name">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <label for="stockAvailable" class="col-sm-6 col-form-label">Stock Available</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="stockAvailable" name="stockAvailable" placeholder="Stock Available">
                            </div>
                        </div>                                            
                    </div>
                    <div class="form-group row">
                        <div class="col-md-4">
                            <label for="purchasePrice" class="col-sm-6 col-form-label">Purchase Price</label>
                            <div class="col-sm-8">
                                <input type="number" class="form-control" id="purchasePrice" name="purchasePrice" placeholder="Purchase Price">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <label for="sellingPrice" class="col-sm-4 col-form-label">Selling Price</label>
                            <div class="col-sm-8">
                                <input type="number" class="form-control" id="sellingPrice" name="sellingPrice" placeholder="Selling Price">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <label for="address" class="col-sm-4 col-form-label">Status</label>
                            <div class="col-sm-8">
                                <select class="form-control" id="status" name="status">
                                    <option value="1">Active</option>
                                    <option value="0">Inactive</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-12">
                            <label for="information" class="col-sm-4 col-form-label">Information</label>
                            <div class="col-sm-12">
                                <textarea name="information" class="form-control" id="information" rows="5"></textarea>
                            </div>
                        </div>
                    </div>
                  </div>
                  <!-- /.card-body -->
                <div class="card-footer">
                    <button type="submit" class="btn btn-default float-right">Submit</button>
                    </div>
              </div>
                <!-- /.card-footer -->
                </form>
              </div>
              <!-- /.card -->
  
            </div>
            <!--/.col (left) -->
          </div>
          <!-- /.row -->
        </div><!-- /.container-fluid -->
      </section>
      <!-- /.content -->
      
@endsection

resources/views/Product/index.blade.php
@extends('layouts.backend.app')

@push('css')
    <!-- DataTables -->
    <link rel="stylesheet" href="{{asset('asset/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css')}}">
    <link rel="stylesheet" href="{{asset('asset/plugins/datatables-responsive/css/responsive.bootstrap4.min.css')}}">
@endpush

@section('content')

    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0 text-dark">Product</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item active">Master</li>
                <li class="breadcrumb-item active">Product</li>
              </ol>
            </div><!-- /.col -->
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content-header -->

          <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Product List</h3>
              <a class="btn btn-info btn-sm float-right" href="{{route('product.create')}}" title="Create">Create</a>
              </div>
              <!-- /.card-header -->
              <ul class="nav nav-tabs" role="tablist" id="myTab">
                <li class="nav-item">
                    <a class="nav-link active" id="active-panel" data-toggle="tab" href="#activePanel" role="tab">Active</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="trash-panel" data-toggle="tab" href="#trashPanel" role="tab">Trash</a>
                </li>
              </ul>
              <div class="card-body">
                <div class="tab-content" id="nav-tabContent">
                    <div class="tab-pane fade in show active" id="activePanel" role="tabpanel">
                        <table id="example1" class="table table-bordered table-striped" style="width: 100%">
                            <thead>
                            <tr>
                              <th>Code</th>
                              <th>Name</th>
                              <th>Purchase Price</th>
                              <th>Information</th>
                              <th>Status</th>
                              <th>Action</th>
                            </tr>
                            </thead>
                            
                            <tfoot>
                            <tr>
                              <th>Code</th>
                              <th>Name</th>
                              <th>Purchase Price</th>
                              <th>Information</th>
                              <th>Status</th>
                              <th>Action</th>
                            </tr>
                            </tfoot>
                          </table> <!-- Table Exaple 1-->
                    </div>

                    <div class="tab-pane fade" id="trashPanel" role="tabpanel">
                        <table id="example2" class="table table-bordered table-striped" style="width: 100%">
                            <thead>
                            <tr>
                              <th>Code</th>
                              <th>Name</th>
                              <th>Purchase Price</th>
                              <th>Information</th>
                              <th>Status</th>
                              <th>Action</th>
                            </tr>
                            </thead>
                            
                            <tfoot>
                            <tr>
                              <th>Code</th>
                              <th>Name</th>
                              <th>Purchase Price</th>
                              <th>Information</th>
                              <th>Status</th>
                              <th>Action</th>
                            </tr>
                            </tfoot>
                          </table>
                    </div>
                </div> <!-- Tab Content Wrapper -->
              </div> <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </section><!-- /.content -->

    {{-- Modal --}}
    <div class="modal fade" id="modal-info">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title">Default Modal</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">

          </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->        
    </div>{{-- /.Modal--}}

@endsection

@push('js')
  <!-- DataTables -->
  <script src="{{asset('asset/plugins/datatables/jquery.dataTables.min.js')}}"></script>
  <script src="{{asset('asset/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js')}}"></script>
  <script src="{{asset('asset/plugins/datatables-responsive/js/dataTables.responsive.min.js')}}"></script>
  <script src="{{asset('asset/plugins/datatables-responsive/js/responsive.bootstrap4.min.js')}}"></script>

  <!-- page script -->
  <script>
    $(function () {
      $("#example1").DataTable({
        "responsive": true,
        "processing": true,
        "pagingType": 'full_numbers',
        "stateSave": false,
        "scrollY": true,
        "scrollX": true,
        ajax:"{{ url('product/datatable') }}",
        order: [0,'desc'],
        columns:[
          {data:'code', name:'code'},
          {data:'name', name:'name'},
          {data:'purchase_price', name:'purchase_price'},
          {data:'information', name:'information'},
          {data:'active',
                render:function(data){
                  if(data=='1'){
                    return '<span class="badge badge-success">Active</span>';
                  }
                  if(data=='0'){
                    return '<span class="badge badge-warning">Inactive</span>';
                  }
                },
          },
          {data:'action', name:'action', searchable: false, sortable:false}
        ]
      });

      $("#example2").DataTable({
        "responsive": true,
        "processing": true,
        "pagingType": 'full_numbers',
        "stateSave": false,
        "scrollY": true,
        "scrollX": true,
        ajax:"{{ url('product/datatableTrash') }}",
        order: [0,'desc'],
        columns:[
          {data:'code', name:'code'},
          {data:'name', name:'name'},
          {data:'purchase_price', name:'purchase_price'},
          {data:'information', name:'information'},
          {data:'active',
                render:function(data){
                  if(data=='2'){
                    return '<span class="badge badge-warning">Deleted</span>';
                  }
                },
          },
          {data:'action', name:'action', searchable: false, sortable:false}
        ]
      });

    });
  </script>

  <script>
    // Confirmation delete data
    function deleteData(dt){
      if(confirm("Are you sure want to delete this data?")){
        $.ajax({
          type: 'DELETE',
          url:$(dt).data("url"),
          data:{
            "_token":"{{csrf_token()}}"
          },
          success:function (response){
            if(response.status){
              location.reload();
            }
          },
          error:function(response){
            console.log(response);
          }
        });
      }
      return false;
    }

    function undoTrash(dt){
      if(confirm("Are you sure want to activate this data?")){
        $.ajax({
          type: 'POST',
          url:$(dt).data("url"),
          data:{
            "_token":"{{csrf_token()}}"
          },
          success:function (response){
            if(response.status){
              location.reload();
            }
          },
          error:function(response){
            console.log(response);
          }
        });
      }
      return false;
    }
  </script>
  <script>
    // Adjust Trash column width
    $(document).ready(function(){
      $('a[data-toggle="tab"]').on('shown.bs.tab', function (e){
        $($.fn.dataTable.tables(true)).DataTable().columns.adjust();

      });
    });
  </script>

  <script>
    $('#modal-info').bind("show.bs.modal", function(e){
        var link = $(e.relatedTarget);
        $(this).find(".modal-body").load(link.attr("href"));
    });
  </script>
@endpush

resources/views/Product/update.blade.php
@extends('layouts.backend.app')

@section('content')
    
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0 text-dark">Product</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item active">Mater</li>
                <li class="breadcrumb-item active">Edit Product</li>
              </ol>
            </div><!-- /.col -->
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content-header -->

          <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
          <div class="row">
            <!-- left column -->
            <div class="col-md-12">
              <!-- Horizontal Form -->
              <div class="card card-info">
                <div class="card-header">
                  <h3 class="card-title">Edit Product</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form class="form-horizontal" method="POST" action="{{route('product.update', $data[0]->id)}}">
                    @method('PUT')
                    @csrf
                  <div class="card-body">
                    <div class="form-group row">
                        <div class="col-md-4">
                            <label for="code" class="col-sm-4 col-form-label">Code</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="code" name="code" value="{{$data[0]->code}}" placeholder="Code">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <label for="name" class="col-sm-4 col-form-label">Name</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="name" name="name" value="{{$data[0]->name}}" placeholder="Name">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <label for="stockAvailable" class="col-sm-6 col-form-label">Stock Available</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="stockAvailable" name="stockAvailable" value="{{$data[0]->stock_available}}" placeholder="Stock Available">
                            </div>
                        </div>                                            
                    </div>
                    <div class="form-group row">
                        <div class="col-md-4">
                            <label for="purchasePrice" class="col-sm-6 col-form-label">Purchase Price</label>
                            <div class="col-sm-8">
                                <input type="number" class="form-control" id="purchasePrice" name="purchasePrice" value="{{$data[0]->purchase_price}}" placeholder="Purchase Price">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <label for="sellingPrice" class="col-sm-4 col-form-label">Selling Price</label>
                            <div class="col-sm-8">
                                <input type="number" class="form-control" id="sellingPrice" name="sellingPrice" value="{{$data[0]->selling_price}}" placeholder="Selling Price">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <label for="address" class="col-sm-4 col-form-label">Status</label>
                            <div class="col-sm-8">
                                <select class="form-control" id="status" name="status">
                                    <option value="1" {{$data[0]->active===1 ? 'selected' : ''}}>Active</option>
                                    <option value="0" {{$data[0]->active===0 ? 'selected' : ''}}>Inactive</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-12">
                            <label for="information" class="col-sm-4 col-form-label">Information</label>
                            <div class="col-sm-12">
                                <textarea name="information" class="form-control" id="information" rows="5">{{$data[0]->information}}</textarea>
                            </div>
                        </div>
                    </div>
                  </div>
                  <!-- /.card-body -->
                <div class="card-footer">
                    <button type="submit" class="btn btn-default float-right">Submit</button>
                    </div>
              </div>
                <!-- /.card-footer -->
                </form>
              </div>
              <!-- /.card -->
  
            </div>
            <!--/.col (left) -->
          </div>
          <!-- /.row -->
        </div><!-- /.container-fluid -->
      </section>
      <!-- /.content -->
      
@endsection