routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('master/vendor', 'Master\VendorController');
Route::get('vendor/datatable', 'Master\VendorController@datatable')->name('vendor/datatable');

Route::resource('master/product', 'Master\ProductController');
Route::get('product/datatable', 'Master\ProductController@datatable')->name('product/datatable');
Route::get('product/datatableTrash', 'Master\ProductController@datatableTrash')->name('product/datatableTrash');
Route::post('product/undoTrash/{id}','Master\ProductController@undotrash')->name('product/undoTrash/{id}');
Route::get('master/product/history/{id}', 'Master\ProductController@history')->name('master/product/history/{id}');

Route::resource('transaction/purchase-order', 'Transaction\PurchaseController');
Route::get('transaction/purchase-order/vendor/popup_media', 'Transaction\PurchaseController@popup_media_vendor')->name('transaction/purchase-order/vendor/popup_media');
Route::get('transaction/purchase-order/product/popup_media/{id_count}', 'Transaction\PurchaseController@popup_media_product')->name('transaction/purchase-order/product/popup_media/{id_count}');
Route::get('browse-vendor/datatable','Master\VendorController@datatable_vendor')->name('browse-vendor/datatable');
Route::get('browse-product/datatable','Master\ProductController@datatable_product')->name('browse-product/datatable');
Route::get('purchase-order/datatable','Transaction\PurchaseController@datatable')->name('purchase-order/datatable');
Route::post('transaction/purchase-order/receive/{id}', 'Transaction\PurchaseController@received')->name('transaction/purchase-order/received/{id}');

Route::resource('transaction/sales', 'Transaction\SaleController');
Route::get('transaction/sales/product/popup_media/{id_count}', 'Transaction\PurchaseController@popup_media_product')->name('transaction/sales/product/popup_media/{id_count}');
Route::get('sales/datatable','Transaction\SaleController@datatable')->name('sales/datatable');
Route::get('transaction/sales/print/{id}','Transaction\SaleController@print')->name('transaction/sales/print/{id}');

Route::get('transaction/stock', 'Transaction\StockController@index')->name('transaction/stock');
Route::get('transaction/stock/product/popup_media', 'Transaction\StockController@popup_media_product')->name('transaction/stock/product/popup_media');
Route::post('transaction/stock', 'Transaction\StockController@update')->name('transaction/stock');
Route::get('stock/report', 'Transaction\StockController@report')->name('stock/report');

app/Http/Controllers/Transaction/PurchaseController.php
<?php

namespace App\Http\Controllers\Transaction;

use App\Http\Controllers\Controller;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Yajra\DataTables\DataTables;
use TJGazel\Toastr\Facades\Toastr;
use Illuminate\Support\Str;
use App\Model\Master\Product;
use App\Model\Purchase\PurchaseD;
use App\Model\Purchase\PurchaseH;
use App\Model\Transaction\Stock;

class PurchaseController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $status ="0";
        $startDate = "01"."-".date('m-Y');
        $endDate = date('d-m-Y');

        if(isset($_GET['startDate']) && (($_GET["startDate"])!=='') ){
            $startDate = $_GET["startDate"];
        }
        if(isset($_GET['endDate']) && (($_GET["endDate"])!=='') ){
            $endDate = $_GET["endDate"];
        }
        if(isset($_GET['status']) && (($_GET["status"])!=='') ){
            $status = $_GET["status"];
        }
        if(!isset($_GET["mode"])){
            $mode = "limited";
        }else{
            
            $mode = $_GET["mode"];
        }
        return view('Transaction.Purchase.index', compact('startDate', 'endDate', 'status', 'mode'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $detail_count = 0;
        return view('Transaction.Purchase.create', compact('detail_count'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = new PurchaseH();
        $data->date = date('Y-m-d', strtotime($request->date));
        $data->no_invoice = $request->invoice_no;
        $data->id_ven = $request->id_ven;
        $data->information = $request->information;
        $data->status ='order';
        $data->active = 1;
        $data->user_modified = Auth::user()->id;
        $total = 0;

        if($data->save()){
            $id_purchase = $data->id;
            if(isset($_POST['id_raw_product'])){
                foreach($_POST['id_raw_product'] as $key=>$id_raw_product):
                    $detail = new PurchaseD();
                    $detail->id_purchase = $data->id;
                    $detail->id_product = $id_raw_product;
                    $detail->total = $_POST['total'][$key];
                    $detail->price = $_POST['price'][$key];
                    $total = $total + ($detail->total *$detail->price);
                    $detail->save();
                endforeach;
            }

            $data = PurchaseH::find($id_purchase);
            $data->total = $total;
            $data->save();

            Toastr::success('Data saved Successfully.', 'Success');
            return redirect()->route('purchase-order.index');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = PurchaseH::with(['user_modify', 'vendor'])->where('id', $id)->get();

        if($data->count()>0){
            $details = PurchaseD::with('product')->where('id_purchase', '=', $data[0]->id)->orderBy('id', 'ASC')->get();
        }
        return view('Transaction.Purchase.view', compact('data', 'details'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $detail_count = 0;
        $data = purchaseH::with('vendor')->where('id', $id)
                    ->where('active', '!=', 2)
                    ->get();
        
        if($data->count() > 0){
            $detail = PurchaseD::with('product')
                        ->where('id_purchase', '=', $data[0]->id)
                        ->orderBy('id', 'ASC')
                        ->get();

            return view('Transaction.Purchase.update', compact('data', 'detail', 'detail_count'));
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = PurchaseH::find($id);
        $data->date = date('Y-m-d', strtotime($request->date));
        $data->no_invoice = $request->invoice_no;
        $data->id_ven = $request->id_ven;
        $data->information = $request->information;
        $data->user_modified = Auth::user()->id;
        $total = 0;

        if($data->save()){
            $delete = PurchaseD::where('id_purchase', '=' ,$id)->delete();
            if(isset($_POST['id_raw_product'])){
                foreach($_POST['id_raw_product'] as $key=>$id_raw_product):
                    $detail = new PurchaseD();
                    $detail->id_purchase = $id;
                    $detail->id_product = $id_raw_product;
                    $detail->total = $_POST['total'][$key];
                    $detail->price = $_POST['price'][$key];
                    $total = $total + ($detail->total *$detail->price);
                    $detail->save();
                endforeach;
            }

            $data = PurchaseH::find($id);
            $data->total = $total;
            $data->save();

            Toastr::success('Data saved successfully.', 'Success');
            return redirect()->route('purchase-order.index');
        }
        Toastr::error('Data cannot be saved successfully.', 'Success');
        return redirect()->route('purchase-order.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = PurchaseH::find($id);
        $data->active = 2;
        $data->user_modified = Auth::user()->id;

        if ($data->save()){
            Toastr::success("Product deleted successfuly", 'Success');
            return new JsonResponse(['status'=>true]);
        }
        else{
            Toastr::error("Product cannot be deleted successfully", 'Error');
            return new JsonResponse(['status'=>false]);
        }
    }

    public function popup_media_vendor(){
        return view('Transaction.Purchase.view_vendor');
    }

    public function popup_media_product($id_count = null){
        return view('Transaction.Purchase.view_product')->with('id_count', $id_count);
    }

    public function datatable(){
        if(isset($_GET['status']) && $_GET['status']!=''){
            $status = $_GET['status'];
        }else{
            $status = 0;
        }

        $startDate = "01"."-".date('m-Y');
        $endDate = date('d-m-Y');
        $mode = "all";

        if(isset($_GET["startDate"]) && ($_GET["startDate"]!='')){
            $startDate = $_GET['startDate'];
        }
        if(isset($_GET["endDate"]) && ($_GET["endDate"]!='')){
            $endDate = $_GET['endDate'];
        }
        if(isset($_GET["mode"])){
            $mode = $_GET['mode'];
        }

        $startDateQuery = date('Y-m-d', strtotime($startDate));
        $endDateQuery = date('Y-m-d', strtotime($endDate));

        if($status == "0"){
            if($mode == "all"){
                $data = PurchaseH::select('purchase_h.*', 'vendors.name')
                            ->leftjoin('vendors', 'purchase_h.id_ven', '=', 'vendors.id')
                            ->where('purchase_h.active', '!=', '2');
                
            }else if($mode = "limited"){
                $data = PurchaseH::select('purchase_h.*', 'vendors.name')
                            ->leftjoin('vendors', 'purchase_h.id_ven', '=', 'vendors.id')
                            ->where('purchase_h.active', '!=', '2')
                            ->whereBetween('purchase_h.date', [$startDateQuery, $endDateQuery]);
            }
        }else{
            if($mode == "all"){
                $data = PurchaseH::select('purchase_h.*', 'vendors.name')
                            ->leftjoin('vendors', 'purchase_h.id_ven', '=', 'vendors.id')
                            ->where('purchase_h.active', '!=', '2')
                            ->where('purchase_h.status', '=', '$status');
                
            }else if($mode = "limited"){
                $data = PurchaseH::select('purchase_h.*', 'vendors.name')
                            ->leftjoin('vendors', 'purchase_h.id_ven', '=', 'vendors.id')
                            ->where('purchase_h.active', '!=', '0')
                            ->where('purchase_h.status', '=', '$status')
                            ->whereBetween('purchase_h.date', [$startDateQuery, $endDateQuery]);
            }
        }

        return DataTables::of($data)
            ->addColumn('action', function($data){
                $url_edit = url('transaction/purchase-order/'.$data->id.'/edit');
                $url = url('transaction/purchase-order/'.$data->id);
                $url_receive = url('transaction/purchase-order/receive/'.$data->id);
                $view = "<a class='btn btn-action btn-primary' href='$url' title='View'><i class='nav-icon fas fa-eye'></i></a>";
                $edit = "";
                $receive = "";
                $delete = "";
                if($data->status == 'order'){
                    $edit = "<a class='btn btn-action btn-warning' href='$url_edit' title='Edit'><i class='nav-icon fas fa-edit'></i></a>";
                    $receive = "<button data-url='$url_receive' onclick='received(this)' class='btn btn-action btn-outline-warning' title='Receive'>Receive</button>";

app/Http/Controllers/Transaction/StockController.php
<?php

namespace App\Http\Controllers\Transaction;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use TJGazel\Toastr\Facades\Toastr;
use App\Model\Master\Product;
use App\Model\Transaction\Stock;

class StockController extends Controller
{
    public function index(){
        return view('Transaction.Stock.index');
    }

    public function update(Request $request){
        $detail = new Stock();
        $detail->id_product = $request->total /1;
        $detail->information = "Stock Correction";
        $detail->type = 'correction';
        $detail->save();

        $data = Product::find($request->id_raw_product);
        $data->stock_total = ($data->stock_total/1) + ($request->total/1);

        if($data->save()){
            Toastr::success('Data saved successfully', 'Success');
            return redirect()->route('transaction/stock');
        }else{
            Toastr::error('Data cannot be saved successfully', 'Error');
            return redirect()->route('transaction/stock');
        }

    }

    public function report(){
        return view('Transaction.Stock.report');
    }

    public function popup_media_product(){
        return view('Transaction.Stock.view_product');
    }
}

resources/views/Transaction/Purchase/create.blade.php
@extends('layouts.backend.app')

@push('css')
    <!-- Date -->
    <link rel="stylesheet" href="{{asset('asset/plugins/jquery-ui/jquery-ui.css')}}">
@endpush

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0 text-dark">Purchase Order</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item">Transaction</li>
                <li class="breadcrumb-item active">Create Purchase Order</li>
              </ol>
            </div><!-- /.col -->
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content-header -->

          <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
          <div class="row">
            <!-- left column -->
            <div class="col-md-12">
              <!-- Horizontal Form -->
              <div class="card card-info">
                <div class="card-header">
                  <h3 class="card-title">Create Purchase Order</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form class="form-horizontal" method="POST" action="{{route('purchase-order.store')}}">
                    @csrf
                  <div class="card-body">
                    <div class="form-group row">
                        <div class="col-md-4">
                            <label for="date" class="col-sm-4 col-form-label">Date</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="date" name="date" placeholder="Date">
                            </div>
                        </div>
                    
                        <div class="col-md-4">
                            <label for="invoice_no" class="col-sm-4 col-form-label">Invoice No.</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="invoice_no" name="invoice_no" placeholder="Invoice No">
                            </div>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-12">
                            <label for="information" class="col-sm-4 col-form-label">Information</label>
                            <div class="col-sm-12">
                                <textarea name="information" class="form-control" id="information" rows="5"></textarea>
                            </div>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-12">
                            <label for="id-ven" class="col-sm-4 col-form-label">Supplier Name</label>
                        </div>
                        <div class="col-sm-4">
                            <input type="hidden" readonly="true" class="form-control" id="id_ven" name="id_ven">
                            <input type="text" readonly="true" name=="name_ven" id="name_ven" class="form-control" placeholder="Supplier Name">
                        </div>
                        <div class="col-cm-4">
                            <a href="/transaction/purchase-order/vendor/popup_media" class="btn btn-info" title="Vendor" data-toggle="modal" data-target="#modal-info">Supplier</a>
                        </div>
                        
                    </div>
                    <div class="col-md-12 field-wrapper">
                        <div class="form-group row">
                            <div class="col-md-12">
                                <label for="id_raw_product" class="col-sm-4 col-form-label">Product Name</label>
                            </div>
                            <div class="col-sm-4">
                                <input type="hidden" readonly="true" class="form-control" id="id_raw_product_1" name="id_raw_product[]">
                                <input type="text" readonly="true" class="form-control" id="name_raw_product_1" name="name_raw_product[]" placeholder="Product Name">
                            </div>
                            <div class="col-sm-1">
                                <a href="/transaction/purchase-order/product/popup_media/1" class="btn btn-info" title="Product" data-toggle="modal" data-target="#modal-info">Product</a>
                            </div>
                            <div class="col-sm-3">
                                <input type="text" class="form-control" id="price_1" name="price[]" placeholder="Price">
                            </div>
                            <div class="col-sm-2">
                                <input type="text" class="form-control" id="total_1" name="total[]" placeholder="Total">
                            </div>
                            <div class="col-sm-2">
                                <a href="javascript:void(0)" class="btn btn-primary add_Button" title="Add Row"><i class="fas fa-plus"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-default float-right">Submit</button>
                </div><!-- /.card-footer -->
              </div> {{-- /.Card info --}}                
                    
                    </form>
              </div> <!-- /.col-md-12 -->
                
              
  
            </div>
            <!--/.col (left) -->
          </div>
          <!-- /.row -->
        </div><!-- /.container-fluid -->
      </section>
      <!-- /.content -->
      {{-- Modal --}}
      <div class="modal fade" id="modal-info">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title">Default Modal</h4>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">

            </div>
          </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->        
      </div>{{-- /.Modal--}}
@endsection

@push('js')

    <script>
        $(document).ready(function(){
            var addButton = $('.add_Button');
            var wrapper = $('.field-wrapper');
            var X = "{{$detail_count +1}}";

            $(addButton).click(function(){
                X++;
                $(wrapper).append(
                    '<div class="form-group row">'+
                        '<div class="col-sm-4">'+
                            '<input type="hidden" readonly="true" class="form-control" id="id_raw_product_'+X+'" name="id_raw_product[]">'+
                            '<input type="text" readonly="true" class="form-control" id="name_raw_product_'+X+'" name="name_raw_product[]" placeholder="Product Name">'+
                        '</div>'+
                        '<div class="col-sm-1">'+
                            '<a href="/transaction/purchase-order/product/popup_media/'+X+'" class="btn btn-info" title="Product" data-toggle="modal" data-target="#modal-info">Product</a>'+
                        '</div>'+
                        '<div class="col-sm-3">'+
                            '<input type="text" class="form-control" id="price_'+X+'" name="price[]" placeholder="Price">'+
                        '</div>'+
                        '<div class="col-sm-2">'+
                            '<input type="text" class="form-control" id="total_'+X+'" name="total[]" placeholder="Total">'+
                        '</div>'+
                        '<div class="col-sm-2">'+
                            '<a href="javascript:void(0)" class="btn btn-danger remove" title="Delete"><i class="fas fa-minus"></i></a>'+
                        '</div>'+
                    '</div>'
                );
            });

            $(wrapper).on('click','.remove',function(e){
                if(confirm("Do you want to delete this row?")){
                    e.preventDefault();
                    $(this).parent().parent().remove();
                }
            });
        });
    </script>
    <script>
        $(function(){
            $('#date').datepicker({
                autoclose:true,
                dateFormat:'dd-mm-yy',
            });
        });
    </script>

    <script>
        $('#modal-info').bind("show.bs.modal", function(e){
            var link = $(e.relatedTarget);
            $(this).find(".modal-body").load(link.attr("href"));
        });
    </script>
@endpush

resources/views/Transaction/Purchase/index.blade.php
@extends('layouts.backend.app')

@push('css')
    <!-- DataTables -->
    <link rel="stylesheet" href="{{asset('asset/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css')}}">
    <link rel="stylesheet" href="{{asset('asset/plugins/datatables-responsive/css/responsive.bootstrap4.min.css')}}">
    <!-- iCheck for checkboxes and radio inputs -->
    <link rel="stylesheet" href="{{asset('asset/plugins/icheck-bootstrap/icheck-bootstrap.min.css')}}">
    <!-- Date -->
    <link rel="stylesheet" href="{{asset('asset/plugins/jquery-ui/jquery-ui.css')}}">
@endpush

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0 text-dark">Purchase</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item">Transaction</li>
                <li class="breadcrumb-item active">Purchase</li>
              </ol>
            </div><!-- /.col -->
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content-header -->

          <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Purchase List</h3>
                <a class="btn btn-info btn-sm float-right" href="{{route('purchase-order.create')}}" title="Create">Create</a>
              </div>
              <!-- /.card-header -->
              <form class="form-horizontal" method="GET" role= "form" autocomplete="off">
                @csrf
                <div class="form-group row">
                    <div class="col-md-12">
                        <label for="address" class="col-sm-4 col-form-label">Status</label>
                        <div class="col-sm-8">
                            <select class="form-control" id="status" name="status">
                                <option value="0" {{$status == '0' ? 'selected' : ''}}>All</option>
                                <option value="order" {{$status == 'order' ? 'selected' : ''}}>Order</option>
                                <option value="received" {{$status == 'received' ? 'selected' : ''}}>Received</option>
                            </select>
                        </div>
                    </div>
                </div> <!-- /.form-group row-->
                <div class="form-group row">
                    <div class="col-md-6">
                        <label for="startDate" class="col-sm-4 col-form-label">Start Date</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control" id="startDate" name="startDate" value="{{$startDate}}">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <label for="endDate" class="col-sm-4 col-form-label">End Date</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control" id="endDate" name="endDate" value="{{$endDate}}">
                        </div>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-6">
                        <!-- checkbox -->
                        <div class="form-group clearfix">
                            <div class="icheck-primary d-inline">
                                <input type="checkbox" id="show-all" name="mode" value="all" {{$mode=='all' ? 'checked' : ''}}>
                                <label for="show-all">Show All</label>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <button type="submit" class="btn btn-default float-right">Submit</button>
                    </div>
                </div>
                
              </form>
              <div class="card-body">
                <table id="example1" class="table table-bordered table-striped" style="width: 100%">
                  <thead>
                  <tr>
                    <th>Invoice</th>
                    <th>Date</th>
                    <th>Vendor Name</th>
                    <th>Total Price</th>
                    <th>Status</th>
                    <th>Action</th>
                  </tr>
                  </thead>
                  
                  <tfoot>
                  <tr>
                    <th>Invoice</th>
                    <th>Date</th>
                    <th>Vendor Name</th>
                    <th>Total Price</th>
                    <th>Status</th>
                    <th>Action</th>
                  </tr>
                  </tfoot>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </section>
    <!-- /.content -->

@endsection

@push('js')
  <!-- DataTables -->
  <script src="{{asset('asset/plugins/datatables/jquery.dataTables.min.js')}}"></script>
  <script src="{{asset('asset/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js')}}"></script>
  <script src="{{asset('asset/plugins/datatables-responsive/js/dataTables.responsive.min.js')}}"></script>
  <script src="{{asset('asset/plugins/datatables-responsive/js/responsive.bootstrap4.min.js')}}"></script>

  <!-- page script -->
  <script>
    $(function () {
      $.ajaxSetup({
        header:{'X-CSRF-TOKEN':$('meta[name="csrf-token"]').attr('content')}
      });
      $("#example1").DataTable({
        "responsive": true,
        "processing": true,
        "pagingType": 'full_numbers',
        "stateSave": false,
        "scrollY": true,
        "scrollX": true,
        ajax:"{!! url('purchase-order/datatable?status='.$status.'&startDate='.$startDate.'&endDate='.$endDate.'&mode='.$mode) !!}",
        order: [0,'desc'],
        columns:[
          {data:'no_invoice', name:'no_invoice'},
          {data:'date', name:'date'},
          {data:'name', name:'name'},
          {data:'total', name:'total'},
          {data:'status',
                render:function(data){
                  if(data=='order'){
                    return '<span class="badge badge-success">Order</span>';
                  }
                  if(data=='received'){
                    return '<span class="badge badge-warning">Received</span>';
                  }
                },
          },
          {data:'action', name:'action', searchable: false, sortable:false}
        ]
      });
    });
  </script>

  <script>
    // Confirmation delete data
    function received(dt){
      if(confirm("Are you sure want to received this product?")){
        $.ajax({
          type: 'POST',
          url:$(dt).data("url"),
          data:{
            "_token":"{{csrf_token()}}"
          },
          success:function (response){
            if(response.status){
              location.reload();
            }
          },
          error:function(response){
            console.log(response);
          }
        });
      }
      return false;
    }
  </script>
  <script>
      $(function(){
          $('#startDate').datepicker({
              autoclose:true,
              dateFormat:'dd-mm-yy',
          });
          $('#endDate').datepicker({
              autoclose:true,
              dateFormat:'dd-mm-yy',
          });
      });
  </script>

<script>
  // Confirmation delete data
  function deleteData(dt){
    if(confirm("Are you sure want to delete this data?")){
      $.ajax({
        type: 'DELETE',
        url:$(dt).data("url"),
        data:{
          "_token":"{{csrf_token()}}"
        },
        success:function (response){
          if(response.status){
            location.reload();
          }
        },
        error:function(response){
          console.log(response);
        }
      });
    }
    return false;
  }
</script>
@endpush